%/****************************************************************************/
%/****************************************************************************/
%/* (C) Copyright 2016 SIGRA Teechnologies GmbH                              */
%/* File Name: tapas_types.m                                                  */
%/* Author: TAPAS Generated                                                   */
%/* Status: Draft Version                                                    */
%/****************************************************************************/
%/****************************************************************************/

function aDbcEnumAvailable = tapas_types_dbc()


aDbcEnumAvailable = {};


Simulink.defineIntEnumType('MCU_VCU_RotationDirection_Rx1_8_t', ... 
{'Backward_Rotation','Forward_Rotation'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_RotationDirection_Rx1_8', ...
'DefaultValue', 'Backward_Rotation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_RotationDirection_Rx1_8_t'];


Simulink.defineIntEnumType('MCU_VCU_PrechargeStatus_Rx1_6_t', ... 
{'Done','Not_done'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_PrechargeStatus_Rx1_6', ...
'DefaultValue', 'Done', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_PrechargeStatus_Rx1_6_t'];


Simulink.defineIntEnumType('MCU_VCU_ModeControl_Rx1_7_t', ... 
{'limited_power_mode','torque'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_ModeControl_Rx1_7', ...
'DefaultValue', 'limited_power_mode', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_ModeControl_Rx1_7_t'];


Simulink.defineIntEnumType('MCU_VCU_MCULVolSelftest_Rx1_12_t', ... 
{'Done','Not_done'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MCULVolSelftest_Rx1_12', ...
'DefaultValue', 'Done', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MCULVolSelftest_Rx1_12_t'];


Simulink.defineIntEnumType('MCU_VCU_AllowedCloseK2_Rx1_10_t', ... 
{'Allowed','Not_Allowed'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_AllowedCloseK2_Rx1_10', ...
'DefaultValue', 'Allowed', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_AllowedCloseK2_Rx1_10_t'];


Simulink.defineIntEnumType('MCU_VCU_Idle_Rx1_9_t', ... 
{'Idle','Other'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_Idle_Rx1_9', ...
'DefaultValue', 'Idle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_Idle_Rx1_9_t'];


Simulink.defineIntEnumType('MCU_VCU_ErrorStatus_Rx1_11_t', ... 
{'Alarm','Common_Fault_speed_limited','Serious_Fault_immediately_stop','No_Fault'}, ... 
[3;2;1;0],...
'Description', 'enum for signal MCU_VCU_ErrorStatus_Rx1_11', ...
'DefaultValue', 'Alarm', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_ErrorStatus_Rx1_11_t'];


Simulink.defineIntEnumType('MCU_VCU_CapacitorDischargeSts_Rx_t', ... 
{'DischargeComplete','Discharging','NotStartDischarging','Reserved'}, ... 
[3;2;1;0],...
'Description', 'enum for signal MCU_VCU_CapacitorDischargeSts_Rx', ...
'DefaultValue', 'DischargeComplete', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_CapacitorDischargeSts_Rx_t'];


Simulink.defineIntEnumType('MCU_VCU_ShutdownStatus_Rx3_2_t', ... 
{'Shutdown','Running'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_ShutdownStatus_Rx3_2', ...
'DefaultValue', 'Shutdown', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_ShutdownStatus_Rx3_2_t'];


Simulink.defineIntEnumType('MCU_VCU_K2ConnectionFail_Rx4_1_t', ... 
{'Fault','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_K2ConnectionFail_Rx4_1', ...
'DefaultValue', 'Fault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_K2ConnectionFail_Rx4_1_t'];


Simulink.defineIntEnumType('MCU_VCU_DCConnectionFail_Rx4_2_t', ... 
{'Fault','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_DCConnectionFail_Rx4_2', ...
'DefaultValue', 'Fault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_DCConnectionFail_Rx4_2_t'];


Simulink.defineIntEnumType('MCU_VCU_ACConnectionFail_Rx4_3_t', ... 
{'Fault','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_ACConnectionFail_Rx4_3', ...
'DefaultValue', 'Fault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_ACConnectionFail_Rx4_3_t'];


Simulink.defineIntEnumType('MCU_VCU_DischargeFailure_Rx4_11_t', ... 
{'Fault','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_DischargeFailure_Rx4_11', ...
'DefaultValue', 'Fault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_DischargeFailure_Rx4_11_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorHWLoseSignal_P_Rx4__t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorHWLoseSignal_P_Rx4_', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorHWLoseSignal_P_Rx4__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorResolve_P_Rx4_9_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorResolve_P_Rx4_9', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorResolve_P_Rx4_9_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorLackphase_P_Rx4_8_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorLackphase_P_Rx4_8', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorLackphase_P_Rx4_8_t'];


Simulink.defineIntEnumType('MCU_VCU_VehicleFaultCircuitRes_R_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_VehicleFaultCircuitRes_R', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_VehicleFaultCircuitRes_R_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCANComuiFailure_P_R_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorCANComuiFailure_P_R', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCANComuiFailure_P_R_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverSpeed_P_Rx4_5_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorOverSpeed_P_Rx4_5', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverSpeed_P_Rx4_5_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorDriverBoardOverT_P__t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorDriverBoardOverT_P_', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorDriverBoardOverT_P__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBlocking_P_Rx4_19_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorBlocking_P_Rx4_19', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBlocking_P_Rx4_19_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverload_P_Rx4_18_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorOverload_P_Rx4_18', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverload_P_Rx4_18_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverTorque_P_Rx4_17_t', ... 
{'Normal','Protection'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorOverTorque_P_Rx4_17', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverTorque_P_Rx4_17_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBusLineOverV_P_Rx4__t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorBusLineOverV_P_Rx4_', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBusLineOverV_P_Rx4__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBusLineUnderV_P_Rx4_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorBusLineUnderV_P_Rx4', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBusLineUnderV_P_Rx4_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorDQOverC_P_Rx4_14_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorDQOverC_P_Rx4_14', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorDQOverC_P_Rx4_14_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCVOverV_P_Rx4_13_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorCVOverV_P_Rx4_13', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCVOverV_P_Rx4_13_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCVReverseConn_P_Rx4_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorCVReverseConn_P_Rx4', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCVReverseConn_P_Rx4_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCVUnderV_P_Rx4_27_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorCVUnderV_P_Rx4_27', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCVUnderV_P_Rx4_27_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorPhaseOverC_P_Rx4_26_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorPhaseOverC_P_Rx4_26', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorPhaseOverC_P_Rx4_26_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBusLineOverC_P_Rx4__t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorBusLineOverC_P_Rx4_', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBusLineOverC_P_Rx4__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverT_P_Rx4_24_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorOverT_P_Rx4_24', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverT_P_Rx4_24_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorIGBTOverT_P_Rx4_23_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorIGBTOverT_P_Rx4_23', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorIGBTOverT_P_Rx4_23_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBridgeUpDown_P_Rx4__t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorBridgeUpDown_P_Rx4_', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBridgeUpDown_P_Rx4__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorDrivePowerUnderV_P__t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorDrivePowerUnderV_P_', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorDrivePowerUnderV_P__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorIGBT_P_Rx4_20_t', ... 
{'Protection','Normal'}, ... 
[1;0],...
'Description', 'enum for signal MCU_VCU_MotorIGBT_P_Rx4_20', ...
'DefaultValue', 'Protection', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorIGBT_P_Rx4_20_t'];


Simulink.defineIntEnumType('VCU_MCU_GearStatus_Tx2_5_t', ... 
{'GearInvalid','RGear','DGear','NGear'}, ... 
[3;2;1;0],...
'Description', 'enum for signal VCU_MCU_GearStatus_Tx2_5', ...
'DefaultValue', 'GearInvalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_GearStatus_Tx2_5_t'];


Simulink.defineIntEnumType('VCU_MCU_FootbrakeSignal_Tx2_4_t', ... 
{'FootbrakeSignalOn','FootbrakeSignalOff'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_FootbrakeSignal_Tx2_4', ...
'DefaultValue', 'FootbrakeSignalOn', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_FootbrakeSignal_Tx2_4_t'];


Simulink.defineIntEnumType('VCU_MCU_HandbrakeSignal_Tx2_3_t', ... 
{'HandbrakePulledup','HandbrakePutdown'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_HandbrakeSignal_Tx2_3', ...
'DefaultValue', 'HandbrakePulledup', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_HandbrakeSignal_Tx2_3_t'];


Simulink.defineIntEnumType('VCU_MCU_BMSToDisconnectK8_Tx1_11_t', ... 
{'AboutToDisconnectK8','K8Connected'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_BMSToDisconnectK8_Tx1_11', ...
'DefaultValue', 'AboutToDisconnectK8', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_BMSToDisconnectK8_Tx1_11_t'];


Simulink.defineIntEnumType('VCU_MCU_EStopStatus_Tx1_10_t', ... 
{'EstopPressed','EstopNotPressed'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_EStopStatus_Tx1_10', ...
'DefaultValue', 'EstopPressed', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_EStopStatus_Tx1_10_t'];


Simulink.defineIntEnumType('VCU_MCU_RelayK1Status_Tx1_2_t', ... 
{'Close','Open'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_RelayK1Status_Tx1_2', ...
'DefaultValue', 'Close', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_RelayK1Status_Tx1_2_t'];


Simulink.defineIntEnumType('VCU_MCU_CapacityDischarge_Tx1_1_t', ... 
{'Discharge','Not_Discharge'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_CapacityDischarge_Tx1_1', ...
'DefaultValue', 'Discharge', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_CapacityDischarge_Tx1_1_t'];


Simulink.defineIntEnumType('VCU_MCU_K2Status_Tx1_3_t', ... 
{'Close','Open'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_K2Status_Tx1_3', ...
'DefaultValue', 'Close', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_K2Status_Tx1_3_t'];


Simulink.defineIntEnumType('VCU_MCU_K2CloseRequest_Tx1_4_t', ... 
{'Close_request','No_close_request'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_K2CloseRequest_Tx1_4', ...
'DefaultValue', 'Close_request', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_K2CloseRequest_Tx1_4_t'];


Simulink.defineIntEnumType('VCU_MCU_K2CloseRequestVali_Tx1_5_t', ... 
{'valid','Invalid'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_K2CloseRequestVali_Tx1_5', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_K2CloseRequestVali_Tx1_5_t'];


Simulink.defineIntEnumType('VCU_MCU_SlopeStopRequest_Tx1_6_t', ... 
{'request','No_request'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_SlopeStopRequest_Tx1_6', ...
'DefaultValue', 'request', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_SlopeStopRequest_Tx1_6_t'];


Simulink.defineIntEnumType('VCU_MCU_ModeControl_Tx1_14_t', ... 
{'limited_power_mode','torque'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_ModeControl_Tx1_14', ...
'DefaultValue', 'limited_power_mode', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_ModeControl_Tx1_14_t'];


Simulink.defineIntEnumType('VCU_MCU_Enable_Tx1_15_t', ... 
{'ON','OFF'}, ... 
[1;0],...
'Description', 'enum for signal VCU_MCU_Enable_Tx1_15', ...
'DefaultValue', 'ON', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_Enable_Tx1_15_t'];


Simulink.defineIntEnumType('VCU_MCU_InverterCommand_Tx1_13_t', ... 
{'idle','backward_rotation','forward_rotation','Stop'}, ... 
[3;2;1;0],...
'Description', 'enum for signal VCU_MCU_InverterCommand_Tx1_13', ...
'DefaultValue', 'idle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_InverterCommand_Tx1_13_t'];


Simulink.defineIntEnumType('VCU_MCU_DrivenCommand_Tx1_12_t', ... 
{'regenerating','driven','invalid'}, ... 
[2;1;0],...
'Description', 'enum for signal VCU_MCU_DrivenCommand_Tx1_12', ...
'DefaultValue', 'regenerating', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_DrivenCommand_Tx1_12_t'];


Simulink.defineIntEnumType('VCU_MCU_CarStatus_Tx1_7_t', ... 
{'Start','Charging','ON','ACC','OFF'}, ... 
[96;80;48;32;16],...
'Description', 'enum for signal VCU_MCU_CarStatus_Tx1_7', ...
'DefaultValue', 'Start', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_MCU_CarStatus_Tx1_7_t'];


Simulink.defineIntEnumType('Alarm_Level_Rx16_6_t', ... 
{'No_Failure','Level_1_failure','Level_2_failure','Level_3_failure','Abnormal','Invalid'}, ... 
[0;1;2;3;254;255],...
'Description', 'enum for signal Alarm_Level_Rx16_6', ...
'DefaultValue', 'No_Failure', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Alarm_Level_Rx16_6_t'];


Simulink.defineIntEnumType('Level1_Battery_Insulation_Rx16_3_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Insulation_Rx16_3', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Insulation_Rx16_3_t'];


Simulink.defineIntEnumType('Level1_Battery_Over_Temperature__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Over_Temperature_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Over_Temperature__t'];


Simulink.defineIntEnumType('Level1_Battery_Over_Voltage_Rx16_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Over_Voltage_Rx16', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Over_Voltage_Rx16_t'];


Simulink.defineIntEnumType('Level1_Battery_Under_Voltage_Rx1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Under_Voltage_Rx1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Under_Voltage_Rx1_t'];


Simulink.defineIntEnumType('Level1_Cell_Over_Voltage_Rx16_4_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Cell_Over_Voltage_Rx16_4', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Cell_Over_Voltage_Rx16_4_t'];


Simulink.defineIntEnumType('Level1_Cell_Under_Voltage_Rx16_5_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Cell_Under_Voltage_Rx16_5', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Cell_Under_Voltage_Rx16_5_t'];


Simulink.defineIntEnumType('Level1_Discharge_Over_Current_Rx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Discharge_Over_Current_Rx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Discharge_Over_Current_Rx_t'];


Simulink.defineIntEnumType('Level1_Feedback_Over_Current_Rx1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Feedback_Over_Current_Rx1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Feedback_Over_Current_Rx1_t'];


Simulink.defineIntEnumType('Level1_SOC_Low_Rx16_1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_SOC_Low_Rx16_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_SOC_Low_Rx16_1_t'];


Simulink.defineIntEnumType('Level2_Battery_Insulation_Rx16_1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Insulation_Rx16_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Insulation_Rx16_1_t'];


Simulink.defineIntEnumType('Level2_Battery_Over_Temperature__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Over_Temperature_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Over_Temperature__t'];


Simulink.defineIntEnumType('Level2_Battery_Over_Voltage_Rx16_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Over_Voltage_Rx16', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Over_Voltage_Rx16_t'];


Simulink.defineIntEnumType('Level2_Battery_Temperature_Diffe_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Temperature_Diffe', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Temperature_Diffe_t'];


Simulink.defineIntEnumType('Level2_Battery_Under_Voltage_Rx1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Under_Voltage_Rx1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Under_Voltage_Rx1_t'];


Simulink.defineIntEnumType('Level2_BMS_Hardware_Failure_Rx16_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_BMS_Hardware_Failure_Rx16', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_BMS_Hardware_Failure_Rx16_t'];


Simulink.defineIntEnumType('Level2_BMS_Inner_Commun_Failure__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_BMS_Inner_Commun_Failure_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_BMS_Inner_Commun_Failure__t'];


Simulink.defineIntEnumType('Level2_Cell_Over_Voltage_Rx16_18_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Cell_Over_Voltage_Rx16_18', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Cell_Over_Voltage_Rx16_18_t'];


Simulink.defineIntEnumType('Level2_Cell_Under_Voltage_Rx16_1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Cell_Under_Voltage_Rx16_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Cell_Under_Voltage_Rx16_1_t'];


Simulink.defineIntEnumType('Level2_Cell_Voltage_Diffe_Rx16_2_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Cell_Voltage_Diffe_Rx16_2', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Cell_Voltage_Diffe_Rx16_2_t'];


Simulink.defineIntEnumType('Level2_Discharge_Over_Current_Rx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Discharge_Over_Current_Rx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Discharge_Over_Current_Rx_t'];


Simulink.defineIntEnumType('Level2_Feedback_Over_Current_Rx1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Feedback_Over_Current_Rx1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Feedback_Over_Current_Rx1_t'];


Simulink.defineIntEnumType('Level2_SOC_Low_Rx16_23_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_SOC_Low_Rx16_23', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_SOC_Low_Rx16_23_t'];


Simulink.defineIntEnumType('Level3_Battery_Insulation_Rx16_2_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Insulation_Rx16_2', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Insulation_Rx16_2_t'];


Simulink.defineIntEnumType('Level3_Battery_Over_Temperature__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Over_Temperature_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Over_Temperature__t'];


Simulink.defineIntEnumType('Level3_Battery_Over_Voltage_Rx16_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Over_Voltage_Rx16', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Over_Voltage_Rx16_t'];


Simulink.defineIntEnumType('Level3_Battery_Temperature_Diffe_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Temperature_Diffe', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Temperature_Diffe_t'];


Simulink.defineIntEnumType('Level3_Battery_Under_Voltage_Rx1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Under_Voltage_Rx1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Under_Voltage_Rx1_t'];


Simulink.defineIntEnumType('Level3_BMS_Inner_Commun_Failure__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_BMS_Inner_Commun_Failure_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_BMS_Inner_Commun_Failure__t'];


Simulink.defineIntEnumType('Level3_Cell_Over_Voltage_Rx16_30_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Cell_Over_Voltage_Rx16_30', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Cell_Over_Voltage_Rx16_30_t'];


Simulink.defineIntEnumType('Level3_Cell_Under_Voltage_Rx16_3_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Cell_Under_Voltage_Rx16_3', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Cell_Under_Voltage_Rx16_3_t'];


Simulink.defineIntEnumType('Level3_Cell_Voltage_Diffe_Rx16_3_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Cell_Voltage_Diffe_Rx16_3', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Cell_Voltage_Diffe_Rx16_3_t'];


Simulink.defineIntEnumType('Level3_Contactor_Failure_Rx16_33_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Contactor_Failure_Rx16_33', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Contactor_Failure_Rx16_33_t'];


Simulink.defineIntEnumType('Level3_Discharge_Over_Current_Rx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Discharge_Over_Current_Rx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Discharge_Over_Current_Rx_t'];


Simulink.defineIntEnumType('Level3_Feedback_Over_Current_Rx1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Feedback_Over_Current_Rx1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Feedback_Over_Current_Rx1_t'];


Simulink.defineIntEnumType('Level3_OnBoard_Commun_Failure_Rx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_OnBoard_Commun_Failure_Rx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_OnBoard_Commun_Failure_Rx_t'];


Simulink.defineIntEnumType('Level3_SOC_Low_Rx16_37_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_SOC_Low_Rx16_37', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_SOC_Low_Rx16_37_t'];


Simulink.defineIntEnumType('Level3_VCU_Commun_Rx16_38_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_VCU_Commun_Rx16_38', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_VCU_Commun_Rx16_38_t'];


Simulink.defineIntEnumType('Status_Contactor_Negative_Rx17_2_t', ... 
{'Open_Circuit','Close_Circuit'}, ... 
[0;1],...
'Description', 'enum for signal Status_Contactor_Negative_Rx17_2', ...
'DefaultValue', 'Open_Circuit', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Contactor_Negative_Rx17_2_t'];


Simulink.defineIntEnumType('Status_Contactor_Positive_Rx17_1_t', ... 
{'Open_Circuit','Closed_Circuit'}, ... 
[0;1],...
'Description', 'enum for signal Status_Contactor_Positive_Rx17_1', ...
'DefaultValue', 'Open_Circuit', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Contactor_Positive_Rx17_1_t'];


Simulink.defineIntEnumType('Status_Contactor_Pre_charge_Rx17_t', ... 
{'Open_Circuit','Close_Circuit'}, ... 
[0;1],...
'Description', 'enum for signal Status_Contactor_Pre_charge_Rx17', ...
'DefaultValue', 'Open_Circuit', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Contactor_Pre_charge_Rx17_t'];


Simulink.defineIntEnumType('Status_Contactor_Slow_Charge_Rx1_t', ... 
{'Open_Circuit','Close_Circuit'}, ... 
[0;1],...
'Description', 'enum for signal Status_Contactor_Slow_Charge_Rx1', ...
'DefaultValue', 'Open_Circuit', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Contactor_Slow_Charge_Rx1_t'];


Simulink.defineIntEnumType('State_Precharge_Rx17_6_t', ... 
{'Precharge_not_done','Precharge_Completed'}, ... 
[0;1],...
'Description', 'enum for signal State_Precharge_Rx17_6', ...
'DefaultValue', 'Precharge_not_done', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'State_Precharge_Rx17_6_t'];


Simulink.defineIntEnumType('Status_Charging_Connection_Rx17__t', ... 
{'Charger_Not_connected','Slow_chargingCC_Connection','Fast_chargingCC2_Connection'}, ... 
[0;1;2],...
'Description', 'enum for signal Status_Charging_Connection_Rx17_', ...
'DefaultValue', 'Charger_Not_connected', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Charging_Connection_Rx17__t'];


Simulink.defineIntEnumType('Status_Charging_Rx17_8_t', ... 
{'Not_charged','Charging','Charging_failure','Charging_Complete'}, ... 
[0;1;2;3],...
'Description', 'enum for signal Status_Charging_Rx17_8', ...
'DefaultValue', 'Not_charged', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Charging_Rx17_8_t'];


Simulink.defineIntEnumType('Status_Contactor_Fast_Charge_Rx1_t', ... 
{'Open_Circuit','Close_Circuit'}, ... 
[0;1],...
'Description', 'enum for signal Status_Contactor_Fast_Charge_Rx1', ...
'DefaultValue', 'Open_Circuit', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Status_Contactor_Fast_Charge_Rx1_t'];


Simulink.defineIntEnumType('VCU_BMS_HV_PowerCmd_Tx3_2_t', ... 
{'HV_OFF','HV_ON','BMSLoadsHighVtgOnItsOwn'}, ... 
[0;1;255],...
'Description', 'enum for signal VCU_BMS_HV_PowerCmd_Tx3_2', ...
'DefaultValue', 'HV_OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_BMS_HV_PowerCmd_Tx3_2_t'];


Simulink.defineIntEnumType('AUX_VCU_AirPump_Fault_Rx19_1_t', ... 
{'Normal','Fault'}, ... 
[0;1],...
'Description', 'enum for signal AUX_VCU_AirPump_Fault_Rx19_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AUX_VCU_AirPump_Fault_Rx19_1_t'];


Simulink.defineIntEnumType('AUX_VCU_AirPump_Status_Rx19_2_t', ... 
{'OFF','ON'}, ... 
[85;170],...
'Description', 'enum for signal AUX_VCU_AirPump_Status_Rx19_2', ...
'DefaultValue', 'OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AUX_VCU_AirPump_Status_Rx19_2_t'];


Simulink.defineIntEnumType('VCU_AUX_AirPump_Command_Tx4_1_t', ... 
{'OFF','ON'}, ... 
[85;170],...
'Description', 'enum for signal VCU_AUX_AirPump_Command_Tx4_1', ...
'DefaultValue', 'OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_AUX_AirPump_Command_Tx4_1_t'];


Simulink.defineIntEnumType('VCU_AUX_DC_DC_Command_Tx4_3_t', ... 
{'OFF','ON'}, ... 
[85;170],...
'Description', 'enum for signal VCU_AUX_DC_DC_Command_Tx4_3', ...
'DefaultValue', 'OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_AUX_DC_DC_Command_Tx4_3_t'];


Simulink.defineIntEnumType('VCU_AUX_OilPump_Command_Tx4_2_t', ... 
{'OFF','ON'}, ... 
[85;170],...
'Description', 'enum for signal VCU_AUX_OilPump_Command_Tx4_2', ...
'DefaultValue', 'OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_AUX_OilPump_Command_Tx4_2_t'];


Simulink.defineIntEnumType('AUX_VCU_DC_DC_Fault_Rx18_6_t', ... 
{'Normal','Fault'}, ... 
[0;1],...
'Description', 'enum for signal AUX_VCU_DC_DC_Fault_Rx18_6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AUX_VCU_DC_DC_Fault_Rx18_6_t'];


Simulink.defineIntEnumType('AUX_VCU_DC_DC_Status_Rx18_5_t', ... 
{'OFF','ON'}, ... 
[85;170],...
'Description', 'enum for signal AUX_VCU_DC_DC_Status_Rx18_5', ...
'DefaultValue', 'OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AUX_VCU_DC_DC_Status_Rx18_5_t'];


Simulink.defineIntEnumType('AUX_VCU_OilPump_Fault_Rx20_1_t', ... 
{'Normal','Fault'}, ... 
[0;1],...
'Description', 'enum for signal AUX_VCU_OilPump_Fault_Rx20_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AUX_VCU_OilPump_Fault_Rx20_1_t'];


Simulink.defineIntEnumType('AUX_VCU_OilPump_Status_Rx20_2_t', ... 
{'OFF','ON'}, ... 
[85;170],...
'Description', 'enum for signal AUX_VCU_OilPump_Status_Rx20_2', ...
'DefaultValue', 'OFF', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AUX_VCU_OilPump_Status_Rx20_2_t'];


Simulink.defineIntEnumType('VCU_Diag_AirPump_Fault_Tx5_1_t', ... 
{'Normal','Fault'}, ... 
[0;1],...
'Description', 'enum for signal VCU_Diag_AirPump_Fault_Tx5_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_Diag_AirPump_Fault_Tx5_1_t'];


Simulink.defineIntEnumType('VCU_Diag_DC_DC_Fault_Tx5_2_t', ... 
{'Normal','Fault'}, ... 
[0;1],...
'Description', 'enum for signal VCU_Diag_DC_DC_Fault_Tx5_2', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_Diag_DC_DC_Fault_Tx5_2_t'];


Simulink.defineIntEnumType('VCU_Diag_OilPump_Fault_Tx5_3_t', ... 
{'Normal','Fault'}, ... 
[0;1],...
'Description', 'enum for signal VCU_Diag_OilPump_Fault_Tx5_3', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_Diag_OilPump_Fault_Tx5_3_t'];


Simulink.defineIntEnumType('Level1_Battery_Insulation_Tx6_2_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Insulation_Tx6_2', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Insulation_Tx6_2_t'];


Simulink.defineIntEnumType('Level1_Battery_Over_Tempera_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Over_Tempera_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Over_Tempera_0000_t'];


Simulink.defineIntEnumType('Level1_Battery_Over_Voltage_Tx6__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Over_Voltage_Tx6_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Over_Voltage_Tx6__t'];


Simulink.defineIntEnumType('Level1_Battery_Under_Voltage_Tx6_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Battery_Under_Voltage_Tx6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Battery_Under_Voltage_Tx6_t'];


Simulink.defineIntEnumType('Level1_Cell_Over_Voltage_Tx6_6_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Cell_Over_Voltage_Tx6_6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Cell_Over_Voltage_Tx6_6_t'];


Simulink.defineIntEnumType('Level1_Cell_Under_Voltage_Tx6_7_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Cell_Under_Voltage_Tx6_7', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Cell_Under_Voltage_Tx6_7_t'];


Simulink.defineIntEnumType('Level1_Discharge_Over_Current_Tx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Discharge_Over_Current_Tx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Discharge_Over_Current_Tx_t'];


Simulink.defineIntEnumType('Level1_Feedback_Over_Current_Tx6_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_Feedback_Over_Current_Tx6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_Feedback_Over_Current_Tx6_t'];


Simulink.defineIntEnumType('Level1_SOC_Low_Tx6_10_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level1_SOC_Low_Tx6_10', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level1_SOC_Low_Tx6_10_t'];


Simulink.defineIntEnumType('Level2_Battery_Insulation_Tx6_11_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Insulation_Tx6_11', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Insulation_Tx6_11_t'];


Simulink.defineIntEnumType('Level2_Battery_Over_Tempera_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Over_Tempera_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Over_Tempera_0000_t'];


Simulink.defineIntEnumType('Level2_Battery_Over_Voltage_Tx6__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Over_Voltage_Tx6_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Over_Voltage_Tx6__t'];


Simulink.defineIntEnumType('Level2_Battery_Temperature__0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Temperature__0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Temperature__0000_t'];


Simulink.defineIntEnumType('Level2_Battery_Under_Voltage_Tx6_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Battery_Under_Voltage_Tx6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Battery_Under_Voltage_Tx6_t'];


Simulink.defineIntEnumType('Level2_BMS_Hardware_Failure_Tx6__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_BMS_Hardware_Failure_Tx6_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_BMS_Hardware_Failure_Tx6__t'];


Simulink.defineIntEnumType('Level2_BMS_Inner_Commun_Fai_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_BMS_Inner_Commun_Fai_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_BMS_Inner_Commun_Fai_0000_t'];


Simulink.defineIntEnumType('Level2_Cell_Over_Voltage_Tx6_18_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Cell_Over_Voltage_Tx6_18', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Cell_Over_Voltage_Tx6_18_t'];


Simulink.defineIntEnumType('Level2_Cell_Under_Voltage_Tx6_19_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Cell_Under_Voltage_Tx6_19', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Cell_Under_Voltage_Tx6_19_t'];


Simulink.defineIntEnumType('Level2_Cell_Voltage_Diffe_Tx6_20_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Cell_Voltage_Diffe_Tx6_20', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Cell_Voltage_Diffe_Tx6_20_t'];


Simulink.defineIntEnumType('Level2_Discharge_Over_Current_Tx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Discharge_Over_Current_Tx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Discharge_Over_Current_Tx_t'];


Simulink.defineIntEnumType('Level2_Feedback_Over_Current_Tx6_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_Feedback_Over_Current_Tx6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_Feedback_Over_Current_Tx6_t'];


Simulink.defineIntEnumType('Level2_SOC_Low_Tx6_23_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level2_SOC_Low_Tx6_23', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level2_SOC_Low_Tx6_23_t'];


Simulink.defineIntEnumType('Level3_Battery_Insulation_Tx6_24_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Insulation_Tx6_24', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Insulation_Tx6_24_t'];


Simulink.defineIntEnumType('Level3_Battery_Over_Tempera_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Over_Tempera_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Over_Tempera_0000_t'];


Simulink.defineIntEnumType('Level3_Battery_Over_Voltage_Tx6__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Over_Voltage_Tx6_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Over_Voltage_Tx6__t'];


Simulink.defineIntEnumType('Level3_Battery_Temperature__0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Battery_Temperature__0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Temperature__0000_t'];


Simulink.defineIntEnumType('Level3_Battery_Under_Voltage_Tx6_t', ... 
{'Normal'}, ... 
[0],...
'Description', 'enum for signal Level3_Battery_Under_Voltage_Tx6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Battery_Under_Voltage_Tx6_t'];


Simulink.defineIntEnumType('Level3_BMS_Inner_Commun_Fai_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_BMS_Inner_Commun_Fai_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_BMS_Inner_Commun_Fai_0000_t'];


Simulink.defineIntEnumType('Level3_Cell_Over_Voltage_Tx6_30_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Cell_Over_Voltage_Tx6_30', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Cell_Over_Voltage_Tx6_30_t'];


Simulink.defineIntEnumType('Level3_Cell_Under_Voltage_Tx6_31_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Cell_Under_Voltage_Tx6_31', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Cell_Under_Voltage_Tx6_31_t'];


Simulink.defineIntEnumType('Level3_Cell_Voltage_Diffe_Tx6_32_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Cell_Voltage_Diffe_Tx6_32', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Cell_Voltage_Diffe_Tx6_32_t'];


Simulink.defineIntEnumType('Level3_Contactor_Failure_Tx6_33_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Contactor_Failure_Tx6_33', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Contactor_Failure_Tx6_33_t'];


Simulink.defineIntEnumType('Level3_Discharge_Over_Current_Tx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Discharge_Over_Current_Tx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Discharge_Over_Current_Tx_t'];


Simulink.defineIntEnumType('Level3_Feedback_Over_Current_Tx6_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_Feedback_Over_Current_Tx6', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_Feedback_Over_Current_Tx6_t'];


Simulink.defineIntEnumType('Level3_OnBoard_Commun_Failure_Tx_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_OnBoard_Commun_Failure_Tx', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_OnBoard_Commun_Failure_Tx_t'];


Simulink.defineIntEnumType('Level3_SOC_Low_Tx6_37_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_SOC_Low_Tx6_37', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_SOC_Low_Tx6_37_t'];


Simulink.defineIntEnumType('Level3_VCU_Commun_Tx6_38_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal Level3_VCU_Commun_Tx6_38', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Level3_VCU_Commun_Tx6_38_t'];


Simulink.defineIntEnumType('MCU_VCU_ACConnectionFail_Tx7_1_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_ACConnectionFail_Tx7_1', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_ACConnectionFail_Tx7_1_t'];


Simulink.defineIntEnumType('MCU_VCU_DCConnectionFail_Tx7_2_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_DCConnectionFail_Tx7_2', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_DCConnectionFail_Tx7_2_t'];


Simulink.defineIntEnumType('MCU_VCU_DischargeFailure_Tx7_3_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_DischargeFailure_Tx7_3', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_DischargeFailure_Tx7_3_t'];


Simulink.defineIntEnumType('MCU_VCU_K2ConnectionFail_Tx7_4_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_K2ConnectionFail_Tx7_4', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_K2ConnectionFail_Tx7_4_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBlocking_P_Tx7_5_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorBlocking_P_Tx7_5', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBlocking_P_Tx7_5_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBridgeUpDown_P_Tx7__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorBridgeUpDown_P_Tx7_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBridgeUpDown_P_Tx7__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBusLineOverC_P_Tx7__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorBusLineOverC_P_Tx7_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBusLineOverC_P_Tx7__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBusLineOverV_P_Tx7__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorBusLineOverV_P_Tx7_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBusLineOverV_P_Tx7__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorBusLineUnderV_P_Tx7_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorBusLineUnderV_P_Tx7', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorBusLineUnderV_P_Tx7_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCANComuiFailure_P_T_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorCANComuiFailure_P_T', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCANComuiFailure_P_T_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCVOverV_P_Tx7_11_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorCVOverV_P_Tx7_11', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCVOverV_P_Tx7_11_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCVReverseConn_P_Tx7_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorCVReverseConn_P_Tx7', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCVReverseConn_P_Tx7_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorCVUnderV_P_Tx7_13_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorCVUnderV_P_Tx7_13', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorCVUnderV_P_Tx7_13_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorDQOverC_P_Tx7_14_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorDQOverC_P_Tx7_14', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorDQOverC_P_Tx7_14_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorDrivePowerUnde_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorDrivePowerUnde_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorDrivePowerUnde_0000_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorDriverBoardOve_0000_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorDriverBoardOve_0000', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorDriverBoardOve_0000_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorHWLoseSignal_P_Tx7__t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorHWLoseSignal_P_Tx7_', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorHWLoseSignal_P_Tx7__t'];


Simulink.defineIntEnumType('MCU_VCU_MotorIGBT_P_Tx7_18_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorIGBT_P_Tx7_18', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorIGBT_P_Tx7_18_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorIGBTOverT_P_Tx7_19_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorIGBTOverT_P_Tx7_19', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorIGBTOverT_P_Tx7_19_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorLackphase_P_Tx7_20_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorLackphase_P_Tx7_20', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorLackphase_P_Tx7_20_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverload_P_Tx7_21_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorOverload_P_Tx7_21', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverload_P_Tx7_21_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverSpeed_P_Tx7_22_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorOverSpeed_P_Tx7_22', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverSpeed_P_Tx7_22_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverT_P_Tx7_23_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorOverT_P_Tx7_23', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverT_P_Tx7_23_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorOverTorque_P_Tx7_24_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorOverTorque_P_Tx7_24', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorOverTorque_P_Tx7_24_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorPhaseOverC_P_Tx7_25_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorPhaseOverC_P_Tx7_25', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorPhaseOverC_P_Tx7_25_t'];


Simulink.defineIntEnumType('MCU_VCU_MotorResolve_P_Tx7_26_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_MotorResolve_P_Tx7_26', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_MotorResolve_P_Tx7_26_t'];


Simulink.defineIntEnumType('MCU_VCU_VehicleFaultCircuitRes_T_t', ... 
{'Normal','Failure'}, ... 
[0;1],...
'Description', 'enum for signal MCU_VCU_VehicleFaultCircuitRes_T', ...
'DefaultValue', 'Normal', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MCU_VCU_VehicleFaultCircuitRes_T_t'];


Simulink.defineIntEnumType('VCU_HMI_MCUErrorStatus_Tx8_2_t', ... 
{'No_Error','Serious_Fault','General_Fault','Alarm'}, ... 
[0;1;10;11],...
'Description', 'enum for signal VCU_HMI_MCUErrorStatus_Tx8_2', ...
'DefaultValue', 'No_Error', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_HMI_MCUErrorStatus_Tx8_2_t'];


Simulink.defineIntEnumType('VCU_HMI_GearStatus_Tx10_2_t', ... 
{'NGear','DGear','RGear','GearInvalid'}, ... 
[0;1;2;3],...
'Description', 'enum for signal VCU_HMI_GearStatus_Tx10_2', ...
'DefaultValue', 'NGear', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_HMI_GearStatus_Tx10_2_t'];


Simulink.defineIntEnumType('VCU_HMI_HandBrake_Tx10_4_t', ... 
{'HandbrakePutDown','HandbrakePulledUp'}, ... 
[0;1],...
'Description', 'enum for signal VCU_HMI_HandBrake_Tx10_4', ...
'DefaultValue', 'HandbrakePutDown', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_HMI_HandBrake_Tx10_4_t'];


Simulink.defineIntEnumType('VCU_HMI_VehicleStatus_Tx10_1_t', ... 
{'Idle','Charging','Discharging','Error'}, ... 
[1;2;3;4],...
'Description', 'enum for signal VCU_HMI_VehicleStatus_Tx10_1', ...
'DefaultValue', 'Idle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VCU_HMI_VehicleStatus_Tx10_1_t'];


end
